### ISSUE TITLE
Start two typers together will cause wrong behavior

### ISSUE THREAD

**Issue by Zhaocl1997** [songwuk/untyper#2]
https://stackblitz.com/edit/vitejs-vite-nhcosl?file=main.js

here is the demo

**Comment by Zhaocl1997** [comment]
never mind, i forgot to use await

**Comment by Zhaocl1997** [comment]
https://stackblitz.com/edit/vitejs-vite-nhcosl?file=main.js

well. i think the wrong behavior exists even if i used await

**Comment by Zhaocl1997** [comment]
After I go through the code, U think it's the cursor class caused the wrong behavior. Maybe need a count to work the cursor like `cursor-1` or something.

**Comment by Zhaocl1997** [comment]
After I went through the code, I think it's the cursor class caused this wrong behavior.
Maybe try to add a unique id for the cursor could fix the issue, like `cursor-1` or something.
Also I suggest that change the cursor class to something like `untyper-cursor-1` cause it might refer to the normal defined class like the unocss etc.(It might not caused any wrong behavior, but I think it's better to do so.)

**Comment by songwuk** [comment]
Thank you for your reply, you should use the ` v0.0.3` version of the code, it can solve the problem.

**Comment by Zhaocl1997** [comment]
Thanks. The wrong behavior has been fixed.
Then I found a new problem that the style cannot be applied to the text correctly.
https://stackblitz.com/edit/vitejs-vite-nhcosl?file=index.html

**Comment by Zhaocl1997** [comment]
Also I find that two typer instant type the text in the same div.
The second div do not contain text.

**Comment by songwuk** [comment]
Thanks. it can solve in `v0.0.4`
